### ISSUE TITLE
Installation not working on latest Kali Linux version

### ISSUE THREAD

**Issue by atlantafan** [simplephishingtoolkit/sptoolkit-rebirth#8]
![screen shot 04-23-15 at 02 31 pm](https://cloud.githubusercontent.com/assets/11218968/7304494/ce7661d2-e9c5-11e4-837c-b9f98a633dc4.JPG)
![screen shot 04-23-15 at 02 32 pm](https://cloud.githubusercontent.com/assets/11218968/7304498/d331ff9c-e9c5-11e4-81ae-ab5bfb7c26cc.JPG)

I have had sptoolkit installed on a former laptop running an earlier version of Kali linux and it installed with no issues.  I am now attempting to install on Kali Linux 1.1.0a and when I get past the screen where it does the environmental checks (which I pass) I start having issues where it shows the Ready to Install screen again on top with the database setup section below it. If I fill out the database setup section It then puts me in a loop where I can never finish the installation.  Any ideas as to what could be causing this?

**Comment by samtarling** [comment]
Hi @atlantafan - I'm looking into this now, there has been a couple of commits which could have caused this. I've assigned this to our next minor release. :)

**Comment by alionroars** [comment]
I've been running into this loop as well. Tried Debian 7, Ubuntu 14.4, and Kali with identical setups.
![screenshot from 2015-06-04 13 33 33](https://cloud.githubusercontent.com/assets/12751910/7991527/5a89ee82-0abe-11e5-8433-155009efdcd0.png)

**Comment by user98765** [comment]
I have the same issue as above - blank screen after clicking "Install database" (using OpenSuse).

**Comment by alionroars** [comment]
JUST got mine to work this afternoon, I had been having a feeling it was the way php was connecting to the db. Sure enough. When I installed php- the module php5-mysql wasn't installed. 
Sudo apt-get php5-mysql
sudo service apache2 restart fixed it for me!

**Comment by atlantafan** [comment]
I am still having the same issue.  php-mysql was already installed on my machine.

**Comment by atlantafan** [comment]
reinstalled from scratch again and it worked this time!  Thanks everyone
